### ISSUE TITLE
While debugging a Demandware script the following exception happened

### ISSUE THREAD

**Issue by ralapaty** [SqrTT/Bart#14] opened 2016-08-31 14:56 UTC
1. Enabled debug and breakpoint in a custom Demandware script (.ds)
2. Script was connecting to a remote service to fetch ratings.
3. Exception help dialog showed up and asked to create an issue, So I did. Let me know if you need more information.

**Atom Version**: 1.9.9
**System**: Microsoft Windows 10 Pro
**Thrown From**: [Bart](https://github.com/SqrTT/bart) package, v1.2.3
### Stack Trace

Uncaught TypeError: this.props.thread.getMembers is not a function

```
At C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\ReactErrorUtils.js:52

TypeError: this.props.thread.getMembers is not a function
    at toggleOpened (C:/Users/Rajendra.Alapaty/.atom/packages/bart/lib/DebuggerView.js:46:31)
    at Object.invokeGuardedCallback (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\ReactErrorUtils.js:26:12)
    at executeDispatch (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\EventPluginUtils.js:89:21)
    at Object.executeDispatchesInOrder (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\EventPluginUtils.js:112:5)
    at executeDispatchesAndRelease (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\EventPluginHub.js:44:22)
    at executeDispatchesAndReleaseTopLevel (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\EventPluginHub.js:55:10)
    at Array.forEach (native)
    at forEachAccumulated (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\forEachAccumulated.js:25:9)
    at Object.EventPluginHub.processEventQueue (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\EventPluginHub.js:229:7)
    at runEventQueueInBatch (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\ReactEventEmitterMixin.js:18:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\ReactEventEmitterMixin.js:29:5)
    at handleTopLevelImpl (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\ReactEventListener.js:73:24)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\Transaction.js:138:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\ReactDefaultBatchingStrategy.js:63:19)
    at Object.batchedUpdates (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\ReactUpdates.js:98:20)
    at ReactEventListener.dispatchEvent (C:\Users\Rajendra.Alapaty\.atom\packages\Bart\node_modules\react\lib\ReactEventListener.js:150:20)
```
### Commands

```
     -4:01.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -3:49.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:45.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:43.1.0 core:undo (atom-text-editor.editor.is-focused)
     -3:41.4.0 core:select-down (atom-text-editor.editor.is-focused)
     -3:41 core:select-up (atom-text-editor.editor.is-focused)
  2x -3:40.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:38.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:21 bart:toggleDebugger (atom-text-editor.editor.is-focused)
     -2:16.7.0 bart:toggleBreakpoint (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Bart, v1.2.3 (active)
git-history, v3.2.0 (inactive)
language-demandware, v0.1.0 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.51.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by SqrTT** [comment] 2016-09-07 20:10
thanx for report, I'll take a look

**Comment by SqrTT** [comment] 2017-05-09 12:44
Hi @ralapaty, could you please try to reproduce in current version (1.6.0)?

**Comment by ralapaty** [comment] 2017-05-09 12:46
Hi Anatolii,

I have moved from working on Demandware and won’t be able to reproduce it as I don’t have access to Demandware environment any more.

Thanks & Regards,
Rajendra Alapaty

**Comment by SqrTT** [comment] 2017-05-09 12:52
Sad to hear, I believe that's not because Bart.

Thanx, for quick response. Closing issue.

**Closed as completed by SqrTT** 2017-05-09 12:52 UTC
